name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: arc-runner-set
    strategy:
      matrix:
        go: [ '1.21', '1.22', '1.23' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Download dependencies
        run: go mod download
        working-directory: sample-code

      - name: Run tests
        run: go test ./... -v
        working-directory: sample-code

      - name: Build binary
        run: go build -v -o main main.go
        working-directory: sample-code
